server {
    listen 80;
    server_name ghd.heiphaistos.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ghd.heiphaistos.org;

    ssl_certificate     /etc/letsencrypt/live/ghd.heiphaistos.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ghd.heiphaistos.org/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root /opt/ghosthanddesk/web;
    index index.html;

    # Headers sécurité
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # WebSocket signaling — proxy vers le serveur Go
    location /ws {
        proxy_pass         http://127.0.0.1:9000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "Upgrade";
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_read_timeout  3600s;
        proxy_send_timeout  3600s;
    }

    # Page de téléchargement statique
    location / {
        try_files $uri $uri/ /index.html;
        expires 1h;
        add_header Cache-Control "public, must-revalidate";
    }
}
